"""red psalter columns

Revision ID: 79c2a4857bad
Revises: 
Create Date: 2024-03-14 11:45:12.089530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79c2a4857bad"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("psalter_pages", sa.Column("psalm_text", sa.Text(), nullable=False))
    op.drop_column("psalter_pages", "page_text")
    op.add_column("psalter_psalms", sa.Column("psalm_text", sa.String(), nullable=False))
    op.drop_column("psalter_psalms", "psalm")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "psalter_psalms",
        sa.Column("psalm", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("psalter_psalms", "psalm_text")
    op.add_column(
        "psalter_pages",
        sa.Column("page_text", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_column("psalter_pages", "psalm_text")
    # ### end Alembic commands ###
